### ISSUE TITLE
Again: ImportError: No module named PyMesh

### ISSUE THREAD

**Issue by gsohler** [PyMesh/PyMesh#135]
I had to recompile PyMesh from scratch and ebcause som sublibs changed and now PyMesh does not run anymore.

I get: 

gigl@localhost PyMesh]$ python -c "import pymesh ; pymesh.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/pymesh2-0.2.1-py2.7-linux-x86_64.egg/pymesh/__init__.py", line 18, in <module>
    from .Mesh import Mesh
  File "/usr/lib64/python2.7/site-packages/pymesh2-0.2.1-py2.7-linux-x86_64.egg/pymesh/Mesh.py", line 5, in <module>
    import PyMesh
ImportError: No module named PyMesh

According to the issues given already i did:

gigl@localhost build]$ grep PYTHON_EXECUTABLE CMakeCache.txt 
PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.6
//ADVANCED property for variable: PYTHON_EXECUTABLE
PYTHON_EXECUTABLE-ADVANCED:INTERNAL=1
[gigl@localhost build]$ grep PYTHON_LIB CMakeCache.txt 
PYTHON_LIBRARY:FILEPATH=/usr/lib64/libpython3.6m.so
PYTHON_LIBRARIES:INTERNAL=/usr/lib64/libpython3.6m.so
//ADVANCED property for variable: PYTHON_LIBRARY
PYTHON_LIBRARY-ADVANCED:INTERNAL=1

This is indeed wrong. But how can i force python 2.7 during compilation ?

**Comment by gsohler** [comment]
Thank you. it worked like a charm!
