### ISSUE TITLE
Error installing PyMesh

### ISSUE THREAD

**Issue by raghavgurbaxani** [PyMesh/PyMesh#141]
Hi 

While installing Pymesh after running python setup.py install - 

Installed /home/raghav/anaconda3/envs/keras/lib/python2.7/site-packages/pymesh2-0.2.1-py2.7-linux-x86_64.egg
Processing dependencies for pymesh2==0.2.1
Finished processing dependencies for pymesh2==0.2.1

However, when $ python 
>>> import pymesh 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/raghav/.local/lib/python2.7/site-packages/pymesh2-0.2.1-py2.7-linux-x86_64.egg/pymesh/__init__.py", line 18, in <module>
    from .Mesh import Mesh
  File "/home/raghav/.local/lib/python2.7/site-packages/pymesh2-0.2.1-py2.7-linux-x86_64.egg/pymesh/Mesh.py", line 5, in <module>
    import PyMesh
ImportError: No module named PyMesh

Any suggestions ?

**Comment by sunnyyum** [comment]
same problem here

**Comment by ijinjay** [comment]
Set the proper path with cmake.

In my case, I use [pyenv](https://github.com/pyenv/pyenv) to manage python versions.

So I run following commands to build the project:

```Zsh
cd $PYMESH_PATH
mkdir build
cd build
cmake -DPYTHON_LIBRARY=/Users/user/.pyenv/versions/anaconda3-5.2.0/lib/libpython3.6m.dylib -DPYTHON_INCLUDE_DIR=/Users/user/.pyenv/versions/anaconda3-5.2.0/include/python3.6m -DPYTHON_EXECUTABLE:FILEPATH=/Users/user/.pyenv/versions/anaconda3-5.2.0/bin/python ..
make -j
cd ..
python setup.py install
```

FYI 😃 ☕️

**Comment by AAcquier** [comment]
Has this been fixed because I have got exactly the same error message that @raghavgurbaxani

**Comment by louzq16** [comment]
@ijinjay ，useful advice. My similar problem has been solved by this way. Thanks!!

**Comment by SimonSolar2C** [comment]
Does this work in a 'standard' ubuntu python3 environment without using anaconda?

**Comment by eyildiz-ugoe** [comment]
I have the same problem on Ubuntu 20.04 and Python 3.8. It's kinda unbelievable that the installation of this package is such a headache. Why not simply introduce a pip package for this? I ended up removing the Pymesh, it took more than 1 hour and that was it for me.
