### ISSUE TITLE
make test fail!  help wanted

### ISSUE THREAD

**Issue by ChenDRAG** [PyMesh/PyMesh#142]
i ran make test and found the error listed below:
[ RUN      ] FaceAreaAttributeTest.3D_tet
/home/chy/PyMesh/tests/src/Attributes/FaceAreaAttributeTest.h:46: Failure
Value of: abs(areas[i])
  Actual: 1
Expected: area
Which is: 2
……
……
……
[  FAILED  ] 1 test, listed below:
[  FAILED  ] FaceAreaAttributeTest.3D_tet

 1 FAILED TEST
tests/src/CMakeFiles/run_Mesh_tests.dir/build.make:57: recipe for target 'tests/src/CMakeFiles/run_Mesh_tests' failed
make[3]: *** [tests/src/CMakeFiles/run_Mesh_tests] Error 1
CMakeFiles/Makefile2:3390: recipe for target 'tests/src/CMakeFiles/run_Mesh_tests.dir/all' failed
make[2]: *** [tests/src/CMakeFiles/run_Mesh_tests.dir/all] Error 2
CMakeFiles/Makefile2:3176: recipe for target 'tests/CMakeFiles/tests.dir/rule' failed
make[1]: *** [tests/CMakeFiles/tests.dir/rule] Error 2
Makefile:766: recipe for target 'tests' failed
make: *** [tests] Error 2

at first ,i ignored this and go on to install pymesh.the installation is successful
but when i import pymesh in python2.7 or python3.6 ,it says no module named pymesh,

on python2

chy@chy:~/PyMesh/build$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymesh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pymesh2-0.2.1-py2.7-linux-x86_64.egg/pymesh/__init__.py", line 18, in <module>
    from .Mesh import Mesh
  File "/usr/local/lib/python2.7/dist-packages/pymesh2-0.2.1-py2.7-linux-x86_64.egg/pymesh/Mesh.py", line 5, in <module>
    import PyMesh
ImportError: No module named PyMesh

on python3
chy@chy:~/PyMesh/build$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymesh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'pymesh'

i do not know how to solve it and really really need your help!thanks!

**Comment by ademsaglam** [comment]
I also have the same problem.

**Comment by YuliangXiu** [comment]
I also have the same problem

FaceAreaAttributeTest.3D_tet failed

**Comment by yun-vis** [comment]
Is this problem solved? I also have it. I am using ubuntu 16.04.

**Comment by xiruiYan** [comment]
Hello, is this problem solved? 
I also have this problem

**Comment by xiruiYan** [comment]
> Is this problem solved? I also have it. I am using ubuntu 16.04.

hi, excuse me, have you solved this problem?  I also met this.

**Comment by yun-vis** [comment]
> > Is this problem solved? I also have it. I am using ubuntu 16.04.
> 
> hi, excuse me, have you solved this problem? I also met this.

No...unfortunately. In the end, I changed to use vtk for my project.

**Comment by xiruiYan** [comment]
> > > Is this problem solved? I also have it. I am using ubuntu 16.04.
> > 
> > 
> > hi, excuse me, have you solved this problem? I also met this.
> 
> No...unfortunately. In the end, I changed to use vtk for my project.

Thanks for your reply. I decide to use another package....

**Comment by Mten7271** [comment]
I did comment out [this test](https://github.com/PyMesh/PyMesh/blob/384ba882b7558ba6e8653ed263c419226c22bddf/tests/src/Attributes/FaceAreaAttributeTest.h#L61) in my local file and resolved this error.
