### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by CharlesFr** [PyMesh/PyMesh#148]
I'm trying to install pymesh using the wheel file as instructed in #94  issue as the Pypi module seems out of date but I get the following error on the import.

Any ideas? Have a missed a step?

```
$ pip install pymesh2-0.2.1-cp36-cp36m-macosx_10_13_x86_64.whl
Processing ./pymesh2-0.2.1-cp36-cp36m-macosx_10_13_x86_64.whl
Installing collected packages: pymesh2
Successfully installed pymesh2-0.2.1
$ python
Python 3.6.5 |Anaconda custom (64-bit)| (default, Apr 26 2018, 08:42:37)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymesh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/pymesh/__init__.py", line 18, in <module>
    from .Mesh import Mesh
  File "/anaconda3/lib/python3.6/site-packages/pymesh/Mesh.py", line 5, in <module>
    import PyMesh
ImportError: dlopen(/anaconda3/lib/python3.6/site-packages/pymesh/lib/PyMesh.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libPyMesh-Assembler.dylib
  Referenced from: /anaconda3/lib/python3.6/site-packages/pymesh/lib/PyMesh.cpython-36m-darwin.so
  Reason: image not found
```

**Comment by sunnyyum** [comment]
I'm saving same problem.

**Comment by Lucas-3D** [comment]
I'm at a loss with this module also

**Comment by sunnyyum** [comment]
I found the solution. If you go into release part, you can download the file with whl extension. Download the this file that matches with your system. (e.g. mac or linux). 
command line "pip install (whl file)" can help you to install pymesh safely.

**Comment by ThibaultGROUEIX** [comment]
I am having the same issue with the wheel file.

**Comment by shadow-guardiann** [comment]
I'm having the same issue even if I install the wheel file. Any fix to this?
