### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by copperwr** [PyMesh/PyMesh#186]
Installed Docker Toolbox. 

All below works without error:
docker run -it pymesh/pymesh
Python 3.6.4 (default, Feb 17 2018, 09:32:33)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymesh

All ok until I execute "mesh = pymesh.load_mesh("TestFile.stl")" when it gives me "OSError: File not found: TestFile.stl"

My problem seems to be with paths.. I don't know how to set it all up so that "load_mesh.py" can find my STL file.  
A bigger issue is that at the moment, I'm just trying to get a basic handle on setting up PyMesh, and ultimately, I need it to work from Spyder (my python IDE) and not just typing commands into the Docker Toolbox command prompt.

As you can probably tell, IT is not my forte and I'd hugely appreciate any help with this.
Thanks

**Comment by AymericFerreira** [comment]
Hello copperwe,

The problem here is that you don't link your docker session to a local directory.

Try something like :

- docker run -it -v full_path_to_TestFile_folder:/data pymesh/pymesh

Then you could load your file with the command if your path is correct :

- mesh = pymesh.load_mesh("data/TestFile.stl")

**Comment by copperwr** [comment]
thanks for that help,... so the next issue is I get this error... where it can't find my file.
I'm not sure if it's as simple as putting the STL file in the right location, or if more setup is required...

PS C:\Users\rober> docker run -it -v /Documents/couplerdesign:/data pymesh/pymesh python3
Python 3.6.8 (default, Mar 27 2019, 08:49:59)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymesh
>>> filename = "PlaneTest.stl"
>>> mesh = pymesh.load_mesh(filename)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymesh/meshio.py", line 26, in load_mesh
    raise IOError("File not found: {}".format(filename));
OSError: File not found: PlaneTest.stl

**Comment by AymericFerreira** [comment]
The path to your file should be :

`filename = data/PlaneTest.stl`
or
`filename = /data/PlaneTest.stl`

The `/data` in the docker command create a new folder data with the content of couplerdesign folder

**Comment by copperwr** [comment]
something still not right unfortunately...

>>> filename = data/PlaneTest.stl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'data' is not defined
>>> filename = "data/PlaneTest.stl"
>>> mesh = pymesh.load_mesh(filename)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymesh/meshio.py", line 26, in load_mesh
    raise IOError("File not found: {}".format(filename));
OSError: File not found: data/PlaneTest.stl

**Comment by AymericFerreira** [comment]
Here is a working example in my case. 

Try to add **/root/** in your docker command : 

`docker run -it -v /Documents/couplerdesign:/root/data pymesh/pymesh`

And then the filename should include the absolute path : 

`import pymesh
filename = "/root/data/PlaneTest.stl"`

It works for me. 

Note that I don't put python3 in my docker command, but the result in both cases are the same.

**Comment by copperwr** [comment]
thanks for the suggestion, still no success with it though:

**Comment by AymericFerreira** [comment]
I'm sorry that it's not working, I don't understand. Maybe I copy/paste it wrong.

Here all my commands if you find something different : 

> sudo docker run -it -v /mnt/4EB2FF89256EC207/PycharmProjects/Scikit-image/betterImages/goodSpine:/root/data pymesh/pymesh python3
> Python 3.6.8 (default, Mar 27 2019, 08:49:59) 
> [GCC 6.3.0 20170516] on linux
> Type "help", "copyright", "credits" or "license" for more information.

>>> import pymesh
>>> pymesh.load_mesh("/root/data/good_spine1_0.ply")
<pymesh.Mesh.Mesh object at 0x7fa5b6d5f358>`

**Comment by AymericFerreira** [comment]
Oh, are you on Windows ? Have you tried to use anti-slash instead of slash  ?

`docker run -it -v C:\Users\rober\Documents\couplerdesign:/root/data pymesh/pymesh`

I used / for docker command because Docker can use Linux containers or Windows containers. Windows syntax uses \ when Linux syntax uses / you should try both if it's not working

Look at your docker parameters to see if you use Windows or Linux containers

**Comment by nicomatton** [comment]
Also, check that you have enabled the drive sharing on Settings (Docker>Settings>Shared Drives)

**Comment by wesleyfox** [comment]
I managed to make it work. I will post the procedure I adopted. I use **Debian 9.13**.  
I believe it will works for debian likes. I also apologize for my google translator english

### I did the following steps to install PyMesh

**Optional** - Set the python version as the system default. I chose to do it because I have other versions of python on my system.
`# update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1
`


**1. Installing dependencies**
_Here I used administrator permission for installation via apt-get._
`# apt install libeigen3-dev libgmp-dev libgmpxx4ldbl libmpfr-dev libboost-dev libboost-thread-dev libtbb-dev python3-dev curl git -y`
_Pip installation_
`# curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py`


**2. clone, part of third parties and requirements**
_As a common user of the system._
``$  git clone https://github.com/PyMesh/PyMesh.git ``
``$ cd PyMesh ``
``$ git submodule update --init ``
``$ export PYMESH_PATH=`pwd` ``
``$ pip install -r $PYMESH_PATH/python/requirements.txt``

**3. Install CMAKE**
_When getting errors in the build step, I noticed that the messages pointed to my outdated version of CMAKE. I upgraded **(version 3.13.4)** using the Debian Buster repository. You may prefer to build from sources. I chose to use apt-get._ 
`# echo "deb http://deb.debian.org/debian buster main" >> /etc/apt/sources.list.d/buster.list`
`# apt update && apt install cmake -y`

**4. Build and install** 
_Still in the PyMesh directory, with a common user._
`$ ./setup.py build`
`$ ./setup.py install  --user `

**5. Test**
`$ python -c "import pymesh; pymesh.test()"`

reference links
https://pymesh.readthedocs.io/en/latest/
https://github.com/PyMesh/PyMesh
https://linuxconfig.org/how-to-change-default-python-version-on-debian-9-stretch-linux
https://pip.pypa.io/en/stable/installing/

Hope this helps.

**Comment by mamunctg** [comment]
> docker run -it -v /Documents/couplerdesign:/root/data pymesh/pymesh


Nice instructions, working my project
