### ISSUE TITLE
Ubuntu 18.04 installation: test fails

### ISSUE THREAD

**Issue by tomathew** [PyMesh/PyMesh#188]
Hello,
I am trying to install PyMesh on Ubuntu 18.04, as directed. Installation and all the thirdparty setup completes successfully. When testing I am getting this error:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pymesh2-0.2.1-py2.7-linux-x86_64.egg/pymesh/__init__.py", line 18, in <module>
    from .Mesh import Mesh
  File "/usr/local/lib/python2.7/dist-packages/pymesh2-0.2.1-py2.7-linux-x86_64.egg/pymesh/Mesh.py", line 5, in <module>
    import PyMesh
ImportError: No module named PyMesh

Also tried the foolproof installation mentioned here in the "Issues" with python3:
gives segmentation fault (core dumped)
What can I do to fix this ?
Thankfully,
Tom

**Comment by brandongk60** [comment]
I was able to get this to work...  Maybe capitalization?  `import pymesh`

```python -c "import pymesh; pymesh.test()"
Running unit tests for pymesh
NumPy version 1.16.4
NumPy relaxed strides checking option: True
NumPy is installed in /home/brandongk/miniconda3/envs/kidneys/lib/python3.7/site-packages/numpy
Python version 3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]
nose version 1.3.7
/home/brandongk/miniconda3/envs/kidneys/lib/python3.7/site-packages/nose/plugins/attrib.py:242: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(value, collections.Callable):
..........................................................................................................Warning: Complex edge loop detected!  Vertex 0 has valance 3

Warning: Complex edge loop detected!  Vertex 0 has valance 3

/home/brandongk/miniconda3/envs/kidneys/lib/python3.7/unittest/case.py:560: RuntimeWarning: TestResult has no addExpectedFailure method, reporting as passes
  RuntimeWarning)
.............................................................S.......
----------------------------------------------------------------------
Ran 175 tests in 2.759s

OK (SKIP=1)
```
