### ISSUE TITLE
ImportError: libmpfr.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by BrandoZhang** [PyMesh/PyMesh#201]
After building and installing PyMesh from source code, I encounter the following problems:

```python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymesh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brando/.local/lib/python3.6/site-packages/pymesh2-0.2.1-py3.6-linux-x86_64.egg/pymesh/__init__.py", line 18, in <module>
    from .Mesh import Mesh
  File "/home/brando/.local/lib/python3.6/site-packages/pymesh2-0.2.1-py3.6-linux-x86_64.egg/pymesh/Mesh.py", line 5, in <module>
    import PyMesh
ImportError: libmpfr.so.6: cannot open shared object file: No such file or directory
```

BTW, I've already run:
```bash
apt-get install \
    libeigen3-dev \
    libgmp-dev \
    libgmpxx4ldbl \
    libmpfr-dev \
    libboost-dev \
    libboost-thread-dev \
    libtbb-dev \
    python3-dev
```
as the documentation stated [here](https://pymesh.readthedocs.io/en/latest/installation.html).

**Comment by Cascades** [comment]
Could you try and find where libmpfr.so.* is?

Maybe look around in `/usr/lib`, `/usr/lib64`, `/usr/local/`, `/opt/local`. Or try a big `find . -iname "libmpfr"`.

**Comment by BrandoZhang** [comment]
> Could you try and find where libmpfr.so.* is?
> 
> Maybe look around in `/usr/lib`, `/usr/lib64`, `/usr/local/`, `/opt/local`. Or try a big `find . -iname "libmpfr"`.

`libmpfr.so.6` is in `/usr/local/lib/`.

**Comment by Cascades** [comment]
You could try running `ldconfig`?

**Comment by BrandoZhang** [comment]
> You could try running `ldconfig`?

The result is:
```bash
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.410.78 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.410.78 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.410.78 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libcuda.so.410.78 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.410.78 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.410.78 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.410.78 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.410.93 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.410.93 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.410.93 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.410.93 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.410.93 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libcuda.so.410.93 is empty, not checked.
/sbin/ldconfig.real: File /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.410.93 is empty, not checked.
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
```

**Comment by Cascades** [comment]
hmmmmm run with sudo?

**Comment by BrandoZhang** [comment]
> hmmmmm run with sudo?

```bash
sbin/ldconfig.real: 文件 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.410.78 为空，未检查。
/sbin/ldconfig.real: 文件 /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.410.78 为空，未检查。
/sbin/ldconfig.real: 文件 /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.410.78 为空，未检查。
/sbin/ldconfig.real: 文件 /usr/lib/x86_64-linux-gnu/libcuda.so.410.78 为空，未检查。
/sbin/ldconfig.real: 文件 /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.410.78 为空，未检查。
/sbin/ldconfig.real: 文件 /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.410.78 为空，未检查。
/sbin/ldconfig.real: 文件 /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.410.78 为空，未检查。
/sbin/ldconfig.real: 文件 /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.410.93 为空，未检查。
/sbin/ldconfig.real: 文件 /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.410.93 为空，未检查。
/sbin/ldconfig.real: 文件 /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.410.93 为空，未检查。
/sbin/ldconfig.real: 文件 /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.410.93 为空，未检查。
/sbin/ldconfig.real: 文件 /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.410.93 为空，未检查。
/sbin/ldconfig.real: 文件 /usr/lib/x86_64-linux-gnu/libcuda.so.410.93 为空，未检查。
/sbin/ldconfig.real: 文件 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.410.93 为空，未检查。
```

"为空，未检查。" means "is empty, not checked".

Seems like I cannot link to the dynamic library.

**Comment by Cascades** [comment]
Have you tried running `import PyMesh` again now?

**Comment by BrandoZhang** [comment]
Hi, sorry for late reply.
I solve this issue by building `mpfr` from their source code. It is very weird, but it works.
Thanks for your patience!!
