### ISSUE TITLE
Build error when executing setup.py. Can't solve Fatal error

### ISSUE THREAD

**Issue by alequark** [PyMesh/PyMesh#242]
I was trying to build PyMesh on a Ubuntu(20.04) partition of my machine and it did not work, so after many attempts I deleted everything and tried again on the same location.
However, again, after following the Installation method once again, this error arises:
`'hel[ 56%] Building CXX object tools/Tetrahedralization/CMakeFiles/lib_Tetrahedralization.dir/TetWild/TetWildEngine.cpp.o
[ 56%] Building CXX object tools/IGL/CMakeFiles/lib_IGL.dir/HarmonicSolver.cpp.o
[ 57%] Building CXX object tools/IGL/CMakeFiles/lib_IGL.dir/MinkowskiSum.cpp.o
[ 57%] Building CXX object tools/ConvexHull/CMakeFiles/lib_ConvexHull.dir/TetGen/TetGenConvexHullEngine.cpp.o
[ 57%] Building CXX object tools/ConvexHull/CMakeFiles/lib_ConvexHull.dir/Triangle/TriangleConvexHullEngine.cpp.o
[ 58%] Linking CXX shared library ../../../python/pymesh/lib/libPyMesh-ConvexHull.so
[ 58%] Built target lib_ConvexHull
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [tools/Tetrahedralization/CMakeFiles/lib_Tetrahedralization.dir/build.make:63: tools/Tetrahedralization/CMakeFiles/lib_Tetrahedralization.dir/TetrahedralizationEngine.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2427: tools/Tetrahedralization/CMakeFiles/lib_Tetrahedralization.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 58%] Linking CXX shared library ../../../python/pymesh/lib/libPyMesh-IGL.so
[ 58%] Built target lib_IGL
make: *** [Makefile:84: all] Error 2
Traceback (most recent call last):
  File "./setup.py", line 105, in <module>
    setup(
  File "/home/alequark/workspace/covid_19/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "./setup.py", line 102, in run
    self.build_pymesh()
  File "./setup.py", line 73, in build_pymesh
    self._build(
  File "./setup.py", line 96, in _build
    check_call(c.split())
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 2.
`

I've tried many things but I can't figure out what is happenning, I think I don't have enough C/C++ knowledge.
It is also worth noting a colleague successfully installed it yesterday and it seems to work fine, and they have the same exact laptop I do, which I find extremely curious.

Is there any way I can fix this?

**Comment by aluo-x** [comment]
The actual error should be higher up. 
I've had to build PyMesh on my local machine & two clusters recently. Many small build errors, but nothing unfixable. @qnzhou Could we have binaries for py3.8? Would avoid having to build this repeatedly.

**Comment by TingtingLiao** [comment]
I have the same problem. Have you solve this problem?

**Comment by aluo-x** [comment]
I got it working ultimately by building a docker container with all the requirements (and openblas-dev & lapack-dev). But if you just need obj loading, I recommend trimesh:
https://github.com/mikedh/trimesh/issues/507#issuecomment-673692260

**Comment by aluo-x** [comment]
I've tried the following:
* Pymesh, quite difficult to build
* Pytorch3d, mesh loading is slow
* Pywavefront, fails on certain shapenet meshes
* Trimesh, great but documentation is complex
