### ISSUE TITLE
MacOS Installation Problems

### ISSUE THREAD

**Issue by potvingab** [PyMesh/PyMesh#259]
Hello,

I tried to follow these instructions https://pymesh.readthedocs.io/en/latest/installation.html without success.
Sorry, that could be an easy fix, I don't have a lot of experience.

1. I downloaded the source (git clone).
`git clone https://github.com/PyMesh/PyMesh.git`
`cd PyMesh`
`git submodule update --init`
`export PYMESH_PATH=pwd`
2. I installed the dependencies with MacPorts (no problem).
`port install`
    `python36 \`
    `eigen3 \`
    `gmp \`
    `mpfr \`
    `tbb \`
    `boost`

3. When I try to build PyMesh, nothing seems to work. 
`./setup.py build`

I get this message:

`running build
== CMake setup ==
-- The C compiler identification is Clang 4.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /Users/gabrielpotvin/opt/anaconda3/bin/x86_64-apple-darwin13.4.0-clang
-- Check for working C compiler: /Users/gabrielpotvin/opt/anaconda3/bin/x86_64-apple-darwin13.4.0-clang - broken
CMake Error at /opt/local/share/cmake-3.18/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler
    /Users/gabrielpotvin/opt/anaconda3/bin/x86_64-apple-darwin13.4.0-clang
  is not able to compile a simple test program.
  It fails with the following output:
    Change Dir: /Users/gabrielpotvin/Desktop/jupyter/Projet/PyMesh/third_party/build/cgal/CMakeFiles/CMakeTmp
    Run Build Command(s):/Users/gabrielpotvin/opt/anaconda3/bin/make cmTC_9dd1e/fast && /Users/gabrielpotvin/opt/anaconda3/bin/make  -f CMakeFiles/cmTC_9dd1e.dir/build.make CMakeFiles/cmTC_9dd1e.dir/build
    make[1]: Entering directory '/Users/gabrielpotvin/Desktop/jupyter/Projet/PyMesh/third_party/build/cgal/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_9dd1e.dir/testCCompiler.c.o
    /Users/gabrielpotvin/opt/anaconda3/bin/x86_64-apple-darwin13.4.0-clang   -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIE -o CMakeFiles/cmTC_9dd1e.dir/testCCompiler.c.o -c /Users/gabrielpotvin/Desktop/jupyter/Projet/PyMesh/third_party/build/cgal/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_9dd1e
    /opt/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9dd1e.dir/link.txt --verbose=1
    /Users/gabrielpotvin/opt/anaconda3/bin/x86_64-apple-darwin13.4.0-clang -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs  CMakeFiles/cmTC_9dd1e.dir/testCCompiler.c.o -o cmTC_9dd1e 
    ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
    ld: dynamic main executables must link with libSystem.dylib for architecture x86_64
    clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [CMakeFiles/cmTC_9dd1e.dir/build.make:106: cmTC_9dd1e] Error 1
    make[1]: Leaving directory '/Users/gabrielpotvin/Desktop/jupyter/Projet/PyMesh/third_party/build/cgal/CMakeFiles/CMakeTmp'
    make: *** [Makefile:140: cmTC_9dd1e/fast] Error 2
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:8 (project)
-- Configuring incomplete, errors occurred!
See also "/Users/gabrielpotvin/Desktop/jupyter/Projet/PyMesh/third_party/build/cgal/CMakeFiles/CMakeOutput.log".
See also "/Users/gabrielpotvin/Desktop/jupyter/Projet/PyMesh/third_party/build/cgal/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "third_party/build.py", line 82, in <module>
    main();
  File "third_party/build.py", line 79, in main
    build(args.package, args.cleanup);
  File "third_party/build.py", line 63, in build
    cleanup=cleanup);
  File "third_party/build.py", line 43, in build_generic
    subprocess.check_call(cmd.split(), cwd=build_dir);
  File "/Users/gabrielpotvin/opt/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/Users/gabrielpotvin/Desktop/jupyter/Projet/PyMesh/third_party/../third_party/cgal', '-DBUILD_SHARED_LIBS=Off', '-DCMAKE_POSITION_INDEPENDENT_CODE=On', '-DWITH_CGAL_ImageIO=Off', '-DWITH_CGAL_Qt5=Off', '-DCMAKE_INSTALL_PREFIX=/Users/gabrielpotvin/Desktop/jupyter/Projet/PyMesh/third_party/../python/pymesh/third_party/']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "./setup.py", line 200, in <module>
    distclass=BinaryDistribution,
  File "/Users/gabrielpotvin/opt/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/gabrielpotvin/opt/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/gabrielpotvin/opt/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/gabrielpotvin/opt/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "./setup.py", line 102, in run
    self.build_third_party()
  File "./setup.py", line 68, in build_third_party
    check_call(c.split())
  File "/Users/gabrielpotvin/opt/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['third_party/build.py', 'cgal']' returned non-zero exit status 1.`

I tried to install CMake, cgal, etc., no success.

4. I tried to build with CMake:
`cd $PYMESH_PATH/third_party`
`mkdir build`
`cd build`
`cmake ..`
`make`
`make install`

I get this message after the line cmake ..:
`CMake Error: The source directory "/Users/gabrielpotvin/Desktop/jupyter/Projet/PyMesh/third_party" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.`

5. I also tried that : https://github.com/PyMesh/PyMesh/issues/5

**Comment by zjhJOJO** [comment]
i met the same problems three days ago,

**Comment by zjhJOJO** [comment]
i finished the pymesh setup just now .i don't use anaconda in my Mac and there is no problem during my second try.

**Comment by svdcvt** [comment]
I met the same problem, but with Ubuntu WSL on Windows 10.

**Comment by jared-slone** [comment]
having similar issues...

**Comment by sakshambh** [comment]
> 

Could you please help me with the same?

**Comment by 10427788** [comment]
I also observed same problem in Ubuntu 22.04LTS distribution. Please let me know the solution to resolve this error. thanks
