### ISSUE TITLE
Installing the python package error

### ISSUE THREAD

**Issue by TzabarDolev** [PyMesh/PyMesh#270]
Hi,
I've built PyMesh from source and managed to perform all operations listed in the README.md file up until install section.
Once i try to install PyMesh by using _python3 ./setup.py build_ trough the terminal it gives:

> running build
> /usr/bin/env: ‘python’: No such file or directory
> Traceback (most recent call last):
>   File "./setup.py", line 106, in <module>
>     setup(
>   File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "./setup.py", line 102, in run
>     self.build_third_party()
>   File "./setup.py", line 68, in build_third_party
>     check_call(c.split())
>   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['third_party/build.py', 'cgal']' returned non-zero exit status 127.

I'm using python3 and ubunto 20.04
Do I need to build CGAL as a seperate service or something like that?

Thanks

**Comment by hrdkjain** [comment]
I am using python3.7 and Ubuntu 20.04 and had a similar problem. Please check if the `git submodule update --init` was successful and the `third_party/cgal` is not empty. I did remove the PyMesh directory and re-pulled everything. Still, the `python3.7 setup.py build `returned the same error. I tried to debug the error and found out that when I executed the build command from debug mode there was no error. I have no idea how it worked this way, but it did work.
