### ISSUE TITLE
ModuleNotFoundError: No module named 'PyMesh'

### ISSUE THREAD

**Issue by MrBenGriffin** [PyMesh/PyMesh#283]
`$ setup.py install`
```
...
Installed /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymesh2-0.3-py3.8-macosx-10.9-x86_64.egg
Processing dependencies for pymesh2==0.3
Finished processing dependencies for pymesh2==0.3
```

$ python3 -c "import pymesh; pymesh.test()"
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymesh2-0.3-py3.8-macosx-10.9-x86_64.egg/pymesh/__init__.py", line 18, in <module>
    from .Mesh import Mesh
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymesh2-0.3-py3.8-macosx-10.9-x86_64.egg/pymesh/Mesh.py", line 5, in <module>
    import PyMesh
ModuleNotFoundError: No module named 'PyMesh'
```

**Comment by pressureless** [comment]
Same error.
Resolved by switching to python3.7

**Comment by schliffen** [comment]
I got the same error. Switched to python3.8 -> problem resolved!
>> python3 -c "import pymesh; pymesh.test()"

Running unit tests for pymesh
NumPy version 1.22.2
NumPy relaxed strides checking option: True
NumPy is installed in /home/ekin/.virtualenvs/gen_dl8/lib/python3.8/site-packages/numpy
Python version 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
nose version 1.3.7
/home/ekin/.virtualenvs/gen_dl8/lib/python3.8/site-packages/nose/plugins/attrib.py:242: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  if isinstance(value, collections.Callable):
............................................................................./home/ekin/.virtualenvs/gen_dl8/lib/python3.8/site-packages/pymesh2-0.3-py3.8-linux-x86_64.egg/pymesh/misc/quaternion.py:16: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  self.__quat = np.array(quat, dtype=np.float)
.............................Warning: Complex edge loop detected!  Vertex 0 has valance 3
Warning: Complex edge loop detected!  Vertex 0 has valance 3
/usr/lib/python3.8/unittest/case.py:608: RuntimeWarning: TestResult has no addExpectedFailure method, reporting as passes
  warnings.warn("TestResult has no addExpectedFailure method, reporting as passes",
.............................................................S......S
----------------------------------------------------------------------
Ran 175 tests in 1.641s
OK (SKIP=2)
