### ISSUE TITLE
Cork installation fails

### ISSUE THREAD

**Issue by Mandelbr0t** [PyMesh/PyMesh#304]
Hi,
im trying to install pymesh on a mac m1 with Big Sur 11.0.1
I can install third party packages manually using `./build.py $package_name` except for cork failing with `ld: symbol(s) not found for architecture x86_64`. 

The output of `gcc -v` is:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Running `python3 -c "import pymesh; pymesh.test()` results in the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/timo/Library/Python/3.8/lib/python/site-packages/pymesh2-0.3-py3.8-macosx-10.14.6-x86_64.egg/pymesh/__init__.py", line 23, in <module>
    from .convex_hull import convex_hull
  File "/Users/timo/Library/Python/3.8/lib/python/site-packages/pymesh2-0.3-py3.8-macosx-10.14.6-x86_64.egg/pymesh/convex_hull.py", line 5, in <module>
    from .triangle import triangle
  File "/Users/timo/Library/Python/3.8/lib/python/site-packages/pymesh2-0.3-py3.8-macosx-10.14.6-x86_64.egg/pymesh/triangle.py", line 4, in <module>
    class triangle(PyMesh.triangle):
AttributeError: module 'PyMesh' has no attribute 'triangle'
```

for which riagn found a possible issue in the cork package.

**Comment by Mandelbr0t** [comment]
Okay apparently wrong libraries were linked. They were built for arm64, in my case it was gmt and mpft
