### ISSUE TITLE
failed to install pymesh2 in windows

### ISSUE THREAD

**Issue by zhang-qiang-github** [PyMesh/PyMesh#342]
I want to install `pymesh` with `pip` by: `pip install pymesh2`, but bugs are reported:

```
Collecting pymesh2
  Downloading https://pypi.doubanio.com/packages/dd/8b/2a34ffcf3a549601fb85621c3235e16c0ee666404bf090afd0dafa08374e/pymesh2-0.1.14.tar.gz (25.4 MB)
     ---------------------------------------- 25.4/25.4 MB 740.3 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pymesh2
  Building wheel for pymesh2 (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      D:\Anaconda\envs\work\lib\site-packages\setuptools\dist.py:760: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        % (opt, underscore_opt)
      running bdist_wheel
      running build
      -- Building for: Visual Studio 17 2022
      CMake Deprecation Warning at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
        Compatibility with CMake < 2.8.12 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
      -- The C compiler identification is MSVC 19.30.30706.0
      -- The CXX compiler identification is MSVC 19.30.30706.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at D:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find GMP (missing: GMP_LIBRARIES)
      Call Stack (most recent call first):
        D:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
        cork/CMake/FindGMP.cmake:20 (find_package_handle_standard_args)
        cork/CMakeLists.txt:35 (find_package)


      -- Configuring incomplete, errors occurred!
      See also "C:/Users/qiang_zhang/AppData/Local/Temp/pip-install-kst2t6fn/pymesh2_8d9ba01625034fecbb5b992af53a5114/third_party/build/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\QIANG_~1\AppData\Local\Temp\pip-install-kst2t6fn\pymesh2_8d9ba01625034fecbb5b992af53a5114\setup.py", line 147, in <module>
          distclass=BinaryDistribution,
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "D:\Anaconda\envs\work\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\QIANG_~1\AppData\Local\Temp\pip-install-kst2t6fn\pymesh2_8d9ba01625034fecbb5b992af53a5114\setup.py", line 80, in run
          self.build_third_party();
        File "C:\Users\QIANG_~1\AppData\Local\Temp\pip-install-kst2t6fn\pymesh2_8d9ba01625034fecbb5b992af53a5114\setup.py", line 55, in build_third_party
          check_call(command.split());
        File "D:\Anaconda\envs\work\lib\subprocess.py", line 363, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '..']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymesh2
  Running setup.py clean for pymesh2
Failed to build pymesh2
Installing collected packages: pymesh2
  Running setup.py install for pymesh2 ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pymesh2 did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      D:\Anaconda\envs\work\lib\site-packages\setuptools\dist.py:760: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        % (opt, underscore_opt)
      running install
      D:\Anaconda\envs\work\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      CMake Deprecation Warning at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
        Compatibility with CMake < 2.8.12 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
      CMake Error at D:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find GMP (missing: GMP_LIBRARIES)
      Call Stack (most recent call first):
        D:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
        cork/CMake/FindGMP.cmake:20 (find_package_handle_standard_args)
        cork/CMakeLists.txt:35 (find_package)


      -- Configuring incomplete, errors occurred!
      See also "C:/Users/qiang_zhang/AppData/Local/Temp/pip-install-kst2t6fn/pymesh2_8d9ba01625034fecbb5b992af53a5114/third_party/build/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\QIANG_~1\AppData\Local\Temp\pip-install-kst2t6fn\pymesh2_8d9ba01625034fecbb5b992af53a5114\setup.py", line 147, in <module>
          distclass=BinaryDistribution,
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\_distutils\command\install.py", line 664, in run
          self.run_command('build')
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "D:\Anaconda\envs\work\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\QIANG_~1\AppData\Local\Temp\pip-install-kst2t6fn\pymesh2_8d9ba01625034fecbb5b992af53a5114\setup.py", line 80, in run
          self.build_third_party();
        File "C:\Users\QIANG_~1\AppData\Local\Temp\pip-install-kst2t6fn\pymesh2_8d9ba01625034fecbb5b992af53a5114\setup.py", line 55, in build_third_party
          check_call(command.split());
        File "D:\Anaconda\envs\work\lib\subprocess.py", line 363, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '..']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pymesh2

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

How can I install `pymesh2` in windows?

**Comment by GuramDuka** [comment]
Hi. I join, same problem.

**Comment by Nathan22211** [comment]
same problem on linux mint, it's not specific to windows

`Collecting pymesh2
  Downloading pymesh2-0.1.14.tar.gz (25.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.4/25.4 MB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pymesh2
  Building wheel for pymesh2 (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      /home/nathan/Desktop/test/venv/lib/python3.10/site-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running bdist_wheel
      running build
      error: [Errno 2] No such file or directory: 'cmake'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymesh2
  Running setup.py clean for pymesh2
Failed to build pymesh2
Installing collected packages: pymesh2
  Running setup.py install for pymesh2 ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pymesh2 did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      /home/nathan/Desktop/test/venv/lib/python3.10/site-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running install
      /home/nathan/Desktop/test/venv/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      error: [Errno 2] No such file or directory: 'cmake'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pymesh2

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`
