### ISSUE TITLE
Compilation failure when building third-party library triangle

### ISSUE THREAD

**Issue by HJ-Xu** [PyMesh/PyMesh#345]
The error message is as follows:

(base) xhj@ryan_server:~/PyMesh/third_party$ python build.py all
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xhj/PyMesh/third_party/build/triangle
Scanning dependencies of target triangle
[ 50%] Building C object CMakeFiles/triangle.dir/triangle.c.o
[100%] Linking C static library libtriangle.a
[100%] Built target triangle
make: *** No rule to make target 'install'.  Stop.
Traceback (most recent call last):
  File "/home/xhj/PyMesh/third_party/build.py", line 86, in <module>
    main();
  File "/home/xhj/PyMesh/third_party/build.py", line 83, in main
    build(args.package, args.cleanup);
  File "/home/xhj/PyMesh/third_party/build.py", line 63, in build
    build(libname, cleanup);
  File "/home/xhj/PyMesh/third_party/build.py", line 79, in build
    build_generic(package, cleanup=cleanup);
  File "/home/xhj/PyMesh/third_party/build.py", line 54, in build_generic
    subprocess.check_call(cmd.split());
  File "/home/xhj/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '/home/xhj/PyMesh/third_party/../third_party/build/triangle', '--target', 'install']' returned non-zero exit status 2.

How do I fix this error?
I eagerly await your help, thank you!
best,
xu

**Comment by orange2350** [comment]
hi,
I would like to quest if you have solved the problem? thank U

**Comment by yanliang3612** [comment]
+1

**Comment by aungpaing-gw** [comment]
+1

**Comment by sugarbeet34** [comment]
+1

**Comment by flybrotherhoi** [comment]
add this to the **third_party/triangle/CMakeLists.txt**
```
install(TARGETS triangle)
install(FILES triangle.h DESTINATION include)
```
