### ISSUE TITLE
can not build draco 

### ISSUE THREAD

**Issue by lizhen-dlut** [PyMesh/PyMesh#365]
/mnt/d/PINN/pymesh/PyMesh/third_party/draco/src/draco/core/hash_utils.h:26:1: error: ‘size_t’ does not name a type
   26 | size_t HashCombine(T1 a, T2 b) {
      | ^~~~~~

**Comment by hernot** [comment]
what ever they check in into github on master it is broken it is not just the size_t and ssize_t it is also numeric_limts and other.
In otherword not useable for now. Either update git submodule to use version which still works or drop draco support for now until draco maintaines have fixed.

**Comment by hernot** [comment]
The same for MMG also has issues

**Comment by abnowack** [comment]
@hernot I ran into this for MMG, did you happen to find a fix?

**Comment by mfs4rd** [comment]
@hernot @abnowack there is a manual fix mentioned in a draco issue [here](https://github.com/google/draco/issues/635)

However rerunning the build yielded further issues. 
```
[ 66%] Building CXX object CMakeFiles/draco_io.dir/src/draco/io/parser_utils.cc.o
PyMesh/third_party/draco/src/draco/io/parser_utils.cc: In function ‘bool draco::parser::ParseFloat(draco::DecoderBuffer*, float*)’:
PyMesh/third_party/draco/src/draco/io/parser_utils.cc:113:16: error: ‘numeric_limits’ is not a member of ‘std’
  113 |       v = std::numeric_limits<double>::infinity();
      |                ^~~~~~~~~~~~~~
PyMesh/third_party/draco/src/draco/io/parser_utils.cc:113:31: error: expected primary-expression before ‘double’
  113 |       v = std::numeric_limits<double>::infinity();
      |                               ^~~~~~
gmake[2]: *** [CMakeFiles/draco_io.dir/build.make:118: CMakeFiles/draco_io.dir/src/draco/io/parser_utils.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:589: CMakeFiles/draco_io.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "PyMesh/third_party/build.py", line 82, in <module>
    main();
    ^^^^^^
  File "PyMesh/third_party/build.py", line 79, in main
    build(args.package, args.cleanup);
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PyMesh/third_party/build.py", line 59, in build
    build(libname, cleanup);
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "PyMesh/third_party/build.py", line 75, in build
    build_generic(package, cleanup=cleanup);
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PyMesh/third_party/build.py", line 47, in build_generic
    subprocess.check_call(cmd.split());
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/filip.sluzewski/.pyenv/versions/3.12.5/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', 'PyMesh/third_party/../third_party/build/draco']' returned non-zero exit status 2.
```

I will post here again if I find a solution but right now I don't see any issue on draco's github. I'll link it here if I make it.

**Comment by mfs4rd** [comment]
I've found what I think the root cause is. This repo downloads and installs forks of its dependencies hosted on this account rather then the original repos. This issue extends to other dependencies as well and this repo is seems abandoned. Try to install [this fork](https://github.com/nuvolos-cloud/PyMesh) instead

**Comment by panallax** [comment]
> @hernot @abnowack there is a manual fix mentioned in a draco issue [here](https://github.com/google/draco/issues/635)
> 
> However rerunning the build yielded further issues.
> 
> ```
> [ 66%] Building CXX object CMakeFiles/draco_io.dir/src/draco/io/parser_utils.cc.o
> PyMesh/third_party/draco/src/draco/io/parser_utils.cc: In function ‘bool draco::parser::ParseFloat(draco::DecoderBuffer*, float*)’:
> PyMesh/third_party/draco/src/draco/io/parser_utils.cc:113:16: error: ‘numeric_limits’ is not a member of ‘std’
>   113 |       v = std::numeric_limits<double>::infinity();
>       |                ^~~~~~~~~~~~~~
> PyMesh/third_party/draco/src/draco/io/parser_utils.cc:113:31: error: expected primary-expression before ‘double’
>   113 |       v = std::numeric_limits<double>::infinity();
>       |                               ^~~~~~
> gmake[2]: *** [CMakeFiles/draco_io.dir/build.make:118: CMakeFiles/draco_io.dir/src/draco/io/parser_utils.cc.o] Error 1
> gmake[1]: *** [CMakeFiles/Makefile2:589: CMakeFiles/draco_io.dir/all] Error 2
> gmake: *** [Makefile:136: all] Error 2
> Traceback (most recent call last):
>   File "PyMesh/third_party/build.py", line 82, in <module>
>     main();
>     ^^^^^^
>   File "PyMesh/third_party/build.py", line 79, in main
>     build(args.package, args.cleanup);
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "PyMesh/third_party/build.py", line 59, in build
>     build(libname, cleanup);
>     ^^^^^^^^^^^^^^^^^^^^^^^
>   File "PyMesh/third_party/build.py", line 75, in build
>     build_generic(package, cleanup=cleanup);
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "PyMesh/third_party/build.py", line 47, in build_generic
>     subprocess.check_call(cmd.split());
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/filip.sluzewski/.pyenv/versions/3.12.5/lib/python3.12/subprocess.py", line 413, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['cmake', '--build', 'PyMesh/third_party/../third_party/build/draco']' returned non-zero exit status 2.
> ```
> 
> I will post here again if I find a solution but right now I don't see any issue on draco's github. I'll link it here if I make it.

I've solved this problem by adding #include < limits > in PyMesh/third_party/draco/src/draco/io/parser_utils.cc. But building fails later due to an issue building mmg2d

**Comment by panallax** [comment]
Finally I could build mmg, and pymesh, by adding SET(CMAKE_C_FLAGS " -fcommon ${CMAKE_C_FLAGS}") in CMakeLists.txt in third_party/mmg.

Solution taken form here: https://github.com/PyMesh/PyMesh/issues/255#issuecomment-1016677844

Buy pymesh can't be imported into python anyway :(

**Comment by panallax** [comment]
Installed correctly out of conda environment with the changes mentioned. Anyway Docker seems to be the easiest way to use pymesh currently.

**Comment by hernot** [comment]
so currently pymesh is only usable for people who do simple things way to complicated (docker). Up to now i do not have any serious needs running a full docker/container environment and just for pymesh its ...

**Comment by shipmech** [comment]
It was installed using Python version 3.11.13, taking into account the mentioned changes.

In fact, it was built on the NVIDIA CUDA image (nvidia/cuda:12.8.0-cudnn-devel-ubuntu22.04), but it should also work on a plain ubuntu:22.04 base. The file is certainly not optimal, but the tests passed.

```dockerfile
FROM ubuntu:22.04

# Set environment variables to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive \
    TZ=UTC \
    PYTHONUNBUFFERED=1

# Update package list and install dependencies for building Python
RUN sed -i '1i deb-src http://archive.ubuntu.com/ubuntu/ jammy main' /etc/apt/sources.list
RUN apt-get update
RUN apt-get build-dep -y python3
RUN apt-get install -y \
    build-essential gdb lcov pkg-config \
    libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev \
    libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev \
    lzma lzma-dev tk-dev uuid-dev zlib1g-dev libmpdec-dev libzstd-dev
RUN apt-get install -y wget
RUN rm -rf /var/lib/apt/lists/*

# Download and install Python 3.11.13 from source (install to /usr/ with --prefix=/usr)
RUN wget https://www.python.org/ftp/python/3.11.13/Python-3.11.13.tgz \
    && tar -xf Python-3.11.13.tgz \
    && cd Python-3.11.13 \
    && ./configure --prefix=/usr --enable-optimizations --enable-shared \
    && make -j$(nproc) \
    && make altinstall \
    && ldconfig \
    && cd .. \
    && rm -rf Python-3.11.13 Python-3.11.13.tgz

# Set Python 3.11.13 as the default Python version (use higher priority to override system)
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 100 \
    && update-alternatives --install /usr/bin/python python /usr/bin/python3.11 100

# Ensure pip is installed and upgraded for Python 3.11
RUN python -m ensurepip \
    && python -m pip install --upgrade pip

# Install system dependencies for PyMesh and general use (minimized based on docs)
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    cmake \
    libeigen3-dev \
    libgmp-dev \
    libgmpxx4ldbl \
    libmpfr-dev \
    libboost-dev \
    libboost-thread-dev \
    libtbb-dev \
    build-essential \
    curl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Clone and init submodules (separated for caching)
RUN git clone https://github.com/PyMesh/PyMesh.git /tmp/PyMesh \
    && cd /tmp/PyMesh \
    && git submodule update --init

# Update Pybind11 submodule to v3.0.0 for Python 3.11 compatibility
RUN cd /tmp/PyMesh/third_party/pybind11 \
    && git remote add upstream https://github.com/pybind/pybind11.git \
    && git fetch upstream --tags \
    && git checkout v2.10.4 \
    && cd /tmp/PyMesh

# Patch setup.py to force CMake to use exact Python 3.11 executable and version
# Also patch setup.cfg to fix SetuptoolsDeprecationWarning (replace dash with underscore)
RUN sed -i "s/ -DPythonLibsNew_FIND_VERSION={}/ -DPython_FIND_VERSION=3.11 -DPython_FIND_VERSION_EXACT=ON -DPython_EXECUTABLE=\\/usr\\/bin\\/python3.11 -DPython_FIND_STRATEGY=LOCATION/g" /tmp/PyMesh/setup.py \
    && sed -i 's/description-file/description_file/g' /tmp/PyMesh/setup.cfg

# Patch and build third-party (with fixes for Draco and MMG)
RUN cd /tmp/PyMesh \
    && sed -i '1i #include <cstddef>' third_party/draco/src/draco/core/hash_utils.h \
    && sed -i '2i #include <cstdint>' third_party/draco/src/draco/core/hash_utils.h \
    && sed -i '1i #include <limits>' third_party/draco/src/draco/io/parser_utils.h \
    && sed -i '1i #include <limits>' third_party/draco/src/draco/io/parser_utils.cc \
    && cd third_party \
    && CFLAGS="-fcommon" CXXFLAGS="-fcommon" ./build.py all \
    && cd .. \
    && rm -rf third_party/build/*  # Clean third-party build dir to save space

# Main PyMesh build with -fcommon to fix multiple definitions in Triangle/Predicates
RUN cd /tmp/PyMesh \
    && CFLAGS="-fcommon" CXXFLAGS="-fcommon" python setup.py build \
    && python setup.py install \
    && cd / \
    && rm -rf /tmp/PyMesh

# Apply compatibility patches for Python 3.11
RUN sed -i '1i import collections' /usr/lib/python3.11/site-packages/pymesh/__init__.py \
    && sed -i '2i import collections.abc' /usr/lib/python3.11/site-packages/pymesh/__init__.py \
    && sed -i '3i collections.Callable = collections.abc.Callable' /usr/lib/python3.11/site-packages/pymesh/__init__.py \
    && sed -i '4i import numpy as np' /usr/lib/python3.11/site-packages/pymesh/__init__.py \
    && sed -i '5i np.float = float' /usr/lib/python3.11/site-packages/pymesh/__init__.py

# Upgrade pip, setuptools, wheel, and install Python dependencies for PyMesh (NumPy, SciPy, Nose)
RUN python -m pip install --upgrade pip setuptools wheel \
    && python -m pip install --no-cache-dir \
    numpy==1.24 \
    scipy==1.11 \
    nose \
    matplotlib==3.10.3

# Run tests to verify installation
RUN python -c "import pymesh; pymesh.test()"

# Set working directory
WORKDIR /app

# Default command (e.g., start a shell or Jupyter if needed)
CMD ["bash"]
```
