### ISSUE TITLE
Cmake Error When running setup.py build.Target "PyMesh" links to target "PyMesh::Wires" but the target was not   found.

### ISSUE THREAD

**Issue by DDDMasterB** [PyMesh/PyMesh#369]
Here is detailed message.

/home/foeveive/require/PyMesh/./setup.py:3: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.command.build import build
/usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
running build
-- Could NOT find MKL (missing: MKL_LIBRARIES MKL_INCLUDE_DIRS MKL_INTERFACE_LIBRARY MKL_SEQUENTIAL_LAYER_LIBRARY MKL_CORE_LIBRARY)
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: atomic chrono date_time system thread
-- Using header-only CGAL
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.48")
-- Boost include dirs: /usr/include
-- Boost libraries:
-- Using gcc version 4 or later. Adding -frounding-math
CMake Warning at cmake/FindMmg.cmake:65 (MESSAGE):

  MMG not found: you can set the 'MMG_BUILD_DIR' environment variable or the
  'MMG_BUILD_DIR' CMake variable to your MMG directory path to help us to
  fill the MMG library paths.

Call Stack (most recent call first):
  cmake/FindAllDependencies.cmake:53 (find_package)
  Settings.cmake:25 (find_package)
  CMakeLists.txt:6 (include)

-- A library with BLAS API not found. Please specify library location.
-- Found PythonInterp: /usr/bin/python3.10 (found suitable version "3.10.12", minimum required is "3.10")
-- pybind11 v2.4.3
CMake Deprecation Warning at tests/external/gmock-1.7.0/CMakeLists.txt:41 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at tests/external/gmock-1.7.0/gtest/CMakeLists.txt:43 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Found PythonInterp: /usr/bin/python3.10 (found version "3.10.12")
-- Configuring done
CMake Error at third_party/pybind11/tools/pybind11Tools.cmake:131 (add_library):
  Target "PyMesh" links to target "PyMesh::Wires" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  python/CMakeLists.txt:1 (PYBIND11_ADD_MODULE)

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "/home/foeveive/require/PyMesh/./setup.py", line 106, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/foeveive/require/PyMesh/./setup.py", line 103, in run
    self.build_pymesh()
  File "/home/foeveive/require/PyMesh/./setup.py", line 75, in build_pymesh
    self._build(
  File "/home/foeveive/require/PyMesh/./setup.py", line 97, in _build
    check_call(c.split())
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '..', '-DCMAKE_BUILD_TYPE=Release', '-DPythonLibsNew_FIND_VERSION=3.10']' returned non-zero exit status 1.

The error message:
![warning](https://github.com/user-attachments/assets/ad1bc4ee-8b5c-47c6-a12f-54ed055f1fe3)

Is this related to the warning below：
![error](https://github.com/user-attachments/assets/107aa7d0-4af2-4791-a0a5-cac2018eb502)

How can I solve the problem?

**Comment by qipaifeiying** [comment]
Look this
-- Could NOT find MKL (missing: MKL_LIBRARIES MKL_INCLUDE_DIRS MKL_INTERFACE_LIBRARY MKL_SEQUENTIAL_LAYER_LIBRARY MKL_CORE_LIBRARY)
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: atomic chrono date_time system thread
-- Using header-only CGAL
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.48")
-- Boost include dirs: /usr/include
-- Boost libraries:
-- Using gcc version 4 or later. Adding -frounding-math
CMake Warning at cmake/FindMmg.cmake:65 (MESSAGE):

MMG not found: you can set the 'MMG_BUILD_DIR' environment variable or the
'MMG_BUILD_DIR' CMake variable to your MMG directory path to help us to
fill the MMG library paths.

try it  `sudo apt-get install libmmg-dev`
The mkl library needs to be installed separately.
run 
```
https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=linux&linux-install-type=online
sudo sh ./l_BaseKit_p_2024.2.1.100.sh -a --silent --cli --eula accept
source /opt/intel/oneapi/setvars.sh
```
