### ISSUE TITLE
Pymesh on docker is not working

### ISSUE THREAD

**Issue by hpbui** [PyMesh/PyMesh#41]
Hello,
After pulling pymesh on docker, I run a test with a python script but it shows an error
"ImportError: libMesh.so: cannot open shared object file: No such file or directory"

It seems that python of the docker container did not find libMesh.so.
Do you have an idea?
Thank you for your help.
Sorry if I post in a wrong place.
Huu Phuoc BUI

**Comment by nubonetics** [comment]
I get the following error when I run: 

> docker run -it pymesh/pymesh

```
Python 3.6.8 (default, Mar 27 2019, 08:49:59) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymesh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pymesh/__init__.py", line 18, in <module>
    from .Mesh import Mesh
  File "/usr/local/lib/python3.6/site-packages/pymesh/Mesh.py", line 5, in <module>
    import PyMesh
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /usr/local/lib/python3.6/site-packages/pymesh/lib/libgeogram.so.1)
>>> 
```

**Comment by qnzhou** [comment]
The glibc problem should have been fixed.  Sorry about the inconvenience. 

```
docker pull pymesh/pymesh
docker run -it --rm pymesh/pymesh python -c "import pymesh; pymesh.test()"
```
